### PR TITLE
chore: EditorConfig file added

### PR DESCRIPTION
**Pull request by AlexWayfer**
It helps in the adaptation settings of the code editor (in my case the Atom
Editor) for this project.

Read more at [editorconfig.org](http://editorconfig.org/)

### CODE REVIEW

**Comment by finom** [comment]
Offtopic: how did you turn on editorconfig support in Atom? I tried few plugins but all of them didn't work :(

**Comment by AlexWayfer** [comment]
@finom [editorconfig](https://atom.io/packages/editorconfig) package.

`Tab Type ⇒ auto` optionally, I think, but I suggest (I haven't seen mention of this setting in the README of the editorconfig-package, should work without it)

**Comment by finom** [comment]
@AlexWayfer I have tried it but it just ignored defined rules. Anyway, other people may not get the same issues. For me ESLint is enough.

**Comment by AlexWayfer** [comment]
@finom It works for me after adding this file, really :) And I hope for others people will too, and you will be able to fix it for you.

**Pull request merged**
